Application/Empired.Games.GuessTheAnimal.WebClient/Models/AnimalViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Empired.Games.GuessTheAnimal.WebClient.Models
{
    public class AnimalViewModel
    {
        public int AnimalID { get; set; }

        [Display(Name="Animal Name")]
        [Required(AllowEmptyStrings =false, ErrorMessage ="Please enter a valid animal name")]
        public string Name { get; set; }

        [Display(Name="Animal's Physical Attribute")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a valid physical attribute")]
        public string PhysicalAttribute { get; set; }


        [Display(Name="Animal's Sound")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a valid animal sound")]
        public string Sound { get; set; }

        [Display(Name="Animal's Color")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a valid animal color")]
        public string Color { get; set; }        
    }
}

Application/Empired.Games.GuessTheAnimal.WebClient/Models/GameViewModel.cs
using Empired.Games.GuessTheAnimal.IRepository;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Empired.Games.GuessTheAnimal.WebClient.Models
{
    public class GameViewModel
    {
        #region Data Binding Properties

        public IList<AnimalViewModel> Animals
        {
            get { return _animals; }
        }

        public IEnumerable<SelectListItem> Colors
        {
            get { return new SelectList(Animals.Select(x => x.Color)); }
        }

        public IEnumerable<SelectListItem> Sounds
        {
            get { return new SelectList(Animals.Select(x => x.Sound)); }
        }

        public IEnumerable<SelectListItem> PhysicalAttributes
        {
            get { return new SelectList(Animals.Select(x => x.PhysicalAttribute)); }
        }

        #endregion

        #region Track User Selections

        public string SelectedColor { get; set; }

        public string SelectedSound { get; set; }

        public string SelectedPhysicalAttribute { get; set; }

        #endregion

        #region Private Properties
        bool IsColorSelected
        {
            get { return !string.IsNullOrEmpty(SelectedColor); }
        }

        bool IsSoundSelected
        {
            get { return !string.IsNullOrEmpty(SelectedSound); }
        }

        bool IsPhysicalAttributeSelected
        {
            get { return !string.IsNullOrEmpty(SelectedPhysicalAttribute); }
        }

        #endregion

        #region Public Properties

        // Check & prevent indeterministic cases
        public bool IsMatchFeasible()
        {
            bool result = true;

            if (IsColorSelected)
            {
                result = _animals.Where(x => x.Color == SelectedColor).SingleOrDefault() != null ? true : false;
            }

            if (IsSoundSelected)
            {
                if (IsColorSelected)
                {
                    result = _animals.Where(x => x.Color == SelectedColor && x.Sound == SelectedSound).SingleOrDefault() != null ? true : false;
                }
                else
                {
                    result = _animals.Where(x => x.Sound == SelectedSound).SingleOrDefault() != null ? true : false;
                }
            }

            return result;
        }

        #endregion

        // Add TypeConverers to cleanly separate DbEntities and Domain Types, Time Permitting
        public GameViewModel(IEnumerable<Animal> animalEntities)
        {
            _animals = new List<AnimalViewModel>();
            if (animalEntities != null)
            {
                foreach (var animalEntity in animalEntities)
                {
                    _animals.Add(new AnimalViewModel { AnimalID = animalEntity.AnimalID, Name = animalEntity.Name, Color = animalEntity.Color, PhysicalAttribute = animalEntity.PhysicalAttribute, Sound = animalEntity.Sound });
                }
            }
        }

        public AnimalViewModel CalculateAnswer()
        {
            AnimalViewModel result = default(AnimalViewModel);

            if (_animals != null && _animals.Count() > 0)
            {
                result = _animals.Where(x => x.Color == SelectedColor
                                        && x.Sound == SelectedSound
                                        && x.PhysicalAttribute == SelectedPhysicalAttribute)
                                        .SingleOrDefault();
            }

            return result;
        }


        IList<AnimalViewModel> _animals;
    }
}

Application/Empired.Games.GuessTheAnimal.WebClient/Controllers/GameController.cs
using Empired.Games.GuessTheAnimal.IRepository;
using Empired.Games.GuessTheAnimal.WebClient.Models;
using System.Web.Mvc;

namespace Empired.Games.GuessTheAnimal.WebClient.Controllers
{
    public class GameController : Controller
    {
        public GameController()
        {
            _repository = new AnimalRepository();

            _viewModel = new GameViewModel(_repository.GetAll());
        }

        public ActionResult Index()
        {
            return View(_viewModel);
        }

        [HttpGet]
        public ActionResult SelectColor()
        {
            return View("SelectColor", _viewModel);
        }

        [HttpPost]
        public ActionResult SelectColor(string selectedColor)
        {
            _viewModel.SelectedColor = selectedColor;

            if (_viewModel.IsMatchFeasible())
            {
                return View("SelectSound", _viewModel);
            }else
            {
                return View("DisplayResult", _viewModel.CalculateAnswer());
            }
        }

 
        [HttpPost]
        [AllowAnonymous]
        public ActionResult SelectSound(string selectedColor, string selectedSound)
        {
            _viewModel.SelectedColor = selectedColor;
            _viewModel.SelectedSound = selectedSound;

            if (_viewModel.IsMatchFeasible())
            {
                return View("SelectPhysicalAttribute", _viewModel);
            }
            else
            {
                return View("DisplayResult", _viewModel.CalculateAnswer());
            }
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult SelectPhysicalAttribute(string selectedColor, string selectedSound, string selectedPhysicalAttribute)
        {
            _viewModel.SelectedColor = selectedColor;
            _viewModel.SelectedSound = selectedSound;
            _viewModel.SelectedPhysicalAttribute = selectedPhysicalAttribute;

            return View("DisplayResult", _viewModel.CalculateAnswer());
        }

        [HttpGet]
        public ActionResult AddAnimal()
        {
            return View("AddAnimal", new AnimalViewModel());
        }


        [HttpPost]
        [AllowAnonymous]
        public ActionResult AddAnimal(AnimalViewModel newAnimal)
        {
            if (ModelState.IsValid)
            {
                _repository.Create(TypeConverters.AnimalTypeConverter.Convert(newAnimal));
                
                return RedirectToAction("Index");
            }

            return View("AddAnimal", newAnimal);
        }

        IRepository<Animal> _repository;
        GameViewModel _viewModel;
    }
}

Application/Empired.Games.GuessTheAnimal.WebClient/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Empired.Games.GuessTheAnimal.WebClient.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }     
    }
}

Application/Empired.Games.GuessTheAnimal.WebClient/Views/Game/AddAnimal.cshtml

@{
    ViewBag.Title = "AddAnimal";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Empired.Games.GuessTheAnimal.WebClient.Models.AnimalViewModel

<h2>Add New Animal</h2>

@using (Html.BeginForm("AddAnimal", "Game", FormMethod.Post))
{

    <table>
        <tr>
            <td>
                @Html.LabelFor(m => m.Name)
            </td>
            <td>
                @Html.TextBoxFor(m => m.Name)
            </td>
            <td>
                @Html.ValidationMessageFor(m => m.Name)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(m => m.Color)
            </td>
            <td>
                @Html.TextBoxFor(m => m.Color)
            </td>
            <td>
                @Html.ValidationMessageFor(m => m.Color)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(m => m.Sound)
            </td>
            <td>
                @Html.TextBoxFor(m => m.Sound)
            </td>
            <td>
                @Html.ValidationMessageFor(m => m.Sound)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(m => m.PhysicalAttribute)
            </td>
            <td>
                @Html.TextBoxFor(m => m.PhysicalAttribute)
            </td>
            <td>
                @Html.ValidationMessageFor(m => m.PhysicalAttribute)
            </td>
        </tr>
    </table>
    <br />

    <button>Create</button>
}

Application/Empired.Games.GuessTheAnimal.WebClient/Views/Game/DisplayResult.cshtml

@{
    ViewBag.Title = "DisplayResult";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Empired.Games.GuessTheAnimal.WebClient.Models.AnimalViewModel

<h2>Results</h2>

@if(Model == null || Model.AnimalID == 0)
{
    <p>Sorry, I could not read your mind which animal you chose. Try Again!</p>
}
else
{
    <p>Awesome! You chose @Model.Name.</p>
}

Application/Empired.Games.GuessTheAnimal.WebClient/Views/Game/Index.cshtml

@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Empired.Games.GuessTheAnimal.WebClient.Models.GameViewModel

<h2>Game On!! Choose an animal from the list of animals</h2>

<div id="divFirstStep" role="application">
    <div class="demo-section k-content wide">
        <label for="lstbChooseAnimal" id="lblChooseAnimal">Choose An Animal</label>
        <br />
        @(Html.Kendo().ListBox()
            .Name("lstbChooseAnimal")
            .HtmlAttributes(new { title = "Animals" })
            .Draggable(false)
            .BindTo(Model.Animals)
            .DataTextField("Name")
        )

        <br />
        <br />
        <h5>Now, I will read your mind and tell you what you chose, click the button below</h5>
        @(Html.Kendo().Button()
            .Name("btnStartGuessing")
            .Content("Read my mind")
            .HtmlAttributes(new { type = "button" })
            .Events(ev => ev.Click("onStartGuessingClick")))

        <br />
        <br />
        <br />
        <h5>Would you like to add a new animal? Yes you can! Click the button below to add a new animal</h5>

        @(Html.Kendo().Button()
            .Name("btnCreate")
            .Content("Add Animal")
            .HtmlAttributes(new { type = "button" })
            .Events(ev => ev.Click("onBtnCreateClick")))
    </div>
</div>

<script>

    function onStartGuessingClick(e) {
        window.location.href = "/Game/SelectColor";
    }

    function onBtnCreateClick(e) {
        window.location.href = "/Game/AddAnimal";
    }
</script>

<style>
    .divFirstStep label {
        margin-bottom: 5px;
        font-weight: bold;
        display: inline-block;
    }

    #animals {
        width: 270px;
    }

    #divFirstStep .demo-section {
        max-width: none;
        width: 515px;
    }

    #divFirstStep .k-listbox {
        width: 600px;
        height: 500px;
    }
</style>





Application/Empired.Games.GuessTheAnimal.WebClient/Views/Game/SelectColor.cshtml

@{
    ViewBag.Title = "Guess Color";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Empired.Games.GuessTheAnimal.WebClient.Models.GameViewModel

<h2>Select the Color of your animal?</h2>

<p>
    @using (Html.BeginForm("SelectColor", "Game", FormMethod.Post))
    {
        @Html.DropDownListFor(m => m.SelectedColor, Model.Colors, "Select a color");

        <br/>
        <br/>
        <button>Next</button>
    }
</p>

Application/Empired.Games.GuessTheAnimal.WebClient/Views/Game/SelectPhysicalAttribute.cshtml

@{
    ViewBag.Title = "SelectPhysicalAttribute";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Empired.Games.GuessTheAnimal.WebClient.Models.GameViewModel

<h2>Select a physical attribute of your animal?</h2>

<p>
    @using (Html.BeginForm("SelectPhysicalAttribute", "Game", FormMethod.Post))
    {
        @Html.HiddenFor(m => m.SelectedColor);
        @Html.HiddenFor(m => m.SelectedSound);
        @Html.DropDownListFor(m => m.SelectedPhysicalAttribute, Model.PhysicalAttributes, "Select a physical attribute");

        <br/>
        <br/>

        <button>Next</button>
    }
</p>

Application/Empired.Games.GuessTheAnimal.WebClient/Views/Game/SelectSound.cshtml

@{
    ViewBag.Title = "GuessSound";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Empired.Games.GuessTheAnimal.WebClient.Models.GameViewModel

<h2>Select the sound that your animal makes?</h2>

<p>
    @using (Html.BeginForm("SelectSound", "Game", FormMethod.Post))
    {
        @Html.HiddenFor(m => m.SelectedColor);
        @Html.DropDownListFor(m => m.SelectedSound, Model.Sounds, "Select sound");


        <br />
        <br />

        <button>Next</button>
    }

</p>

Application/Empired.Games.GuessTheAnimal.WebClient/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Guess The Animal Game</h1>
    <h3>Press Start to play the fun game!</h3>
@(Html.Kendo().Button()
    .Name("btnStart")
    .Content("Start")
    .HtmlAttributes(new { type = "button" })
    .Events(ev => ev.Click("onClick")))
</div>

<script>
    function onClick(e) {
        window.location.href = "/Game";
    }
</script>

<style>
</style>

Application/Empired.Games.GuessTheAnimal.WebClient/Views/Shared/EditorTemplates/Boolean.cshtml
@model bool?

@(Html.Kendo().CheckBoxFor(m => m))

Application/Empired.Games.GuessTheAnimal.WebClient/Views/Shared/EditorTemplates/Currency.cshtml
@model decimal?

@(Html.Kendo().CurrencyTextBoxFor(m => m)      
      .HtmlAttributes(new {style="width:100%"})
      .Min(0)
)



Application/Empired.Games.GuessTheAnimal.WebClient/Views/Shared/EditorTemplates/Date.cshtml
@model DateTime?

@(Html.Kendo().DatePickerFor(m => m))

Application/Empired.Games.GuessTheAnimal.WebClient/Views/Shared/EditorTemplates/DateTime.cshtml
@model DateTime?

@(Html.Kendo().DateTimePickerFor(m => m))

Application/Empired.Games.GuessTheAnimal.WebClient/Views/Shared/EditorTemplates/Email.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox" })

Application/Empired.Games.GuessTheAnimal.WebClient/Views/Shared/EditorTemplates/EmailAddress.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox", type="email" })

Application/Empired.Games.GuessTheAnimal.WebClient/Views/Shared/EditorTemplates/GridForeignKey.cshtml
@model object
           
@(
 Html.Kendo().DropDownListFor(m => m)        
        .BindTo((SelectList)ViewData[ViewData.TemplateInfo.GetFullHtmlFieldName("") + "_Data"])
)

Application/Empired.Games.GuessTheAnimal.WebClient/Views/Shared/EditorTemplates/Integer.cshtml
@model int?

@(Html.Kendo().IntegerTextBoxFor(m => m)
      .HtmlAttributes(new { style = "width:100%" })
      .Min(int.MinValue)
      .Max(int.MaxValue)
)

Application/Empired.Games.GuessTheAnimal.WebClient/Views/Shared/EditorTemplates/Number.cshtml
@model double?

@(Html.Kendo().NumericTextBoxFor(m => m)
      .HtmlAttributes(new { style = "width:100%" })
)

Application/Empired.Games.GuessTheAnimal.WebClient/Views/Shared/EditorTemplates/Password.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox", type="password" })

Application/Empired.Games.GuessTheAnimal.WebClient/Views/Shared/EditorTemplates/String.cshtml
@model object 

@Html.Kendo().TextBoxFor(model => model)

Application/Empired.Games.GuessTheAnimal.WebClient/Views/Shared/EditorTemplates/Time.cshtml
@model DateTime?
           
@(Html.Kendo().TimePickerFor(m => m))

Application/Empired.Games.GuessTheAnimal.WebClient/Views/Shared/EditorTemplates/Url.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox", type="url" })

Application/Empired.Games.GuessTheAnimal.WebClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html> 
    <head>
        <title>@ViewBag.Title - My Telerik MVC Application</title>
        <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" type="text/css" />

        @* Content-box fixes as per http://docs.telerik.com/kendo-ui/third-party/using-kendo-with-twitter-bootstrap article  *@
        <link href="@Url.Content("~/Content/box-sizing-fixes.css")" rel="stylesheet" type="text/css" />

        <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />

        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")

    	<link href="https://kendo.cdn.telerik.com/2017.2.504/styles/kendo.common-bootstrap.min.css" rel="stylesheet" type="text/css" />
	<link href="https://kendo.cdn.telerik.com/2017.2.504/styles/kendo.mobile.all.min.css" rel="stylesheet" type="text/css" />
	<link href="https://kendo.cdn.telerik.com/2017.2.504/styles/kendo.bootstrap.min.css" rel="stylesheet" type="text/css" />
	<script src="https://kendo.cdn.telerik.com/2017.2.504/js/jquery.min.js"></script>
	<script src="https://kendo.cdn.telerik.com/2017.2.504/js/jszip.min.js"></script>
	<script src="https://kendo.cdn.telerik.com/2017.2.504/js/kendo.all.min.js"></script>
	<script src="https://kendo.cdn.telerik.com/2017.2.504/js/kendo.aspnetmvc.min.js"></script>
	<script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>
</head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button id="configure" class="k-rpanel-toggle k-button btn-toggle"><span class="k-icon k-i-hbars"></span></button>
                    @Html.ActionLink("Empired Games", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>

                <div id="responsive-panel" class="navbar-left">
                    @(Html.Kendo().Menu()
                                .Name("Menu")
                                .Items(items =>
                                {})
                    )
                </div>
            </div>
        </div>
        <div class="body-content">
            <div class="container">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year - Empired Coding Application Challenge</p>
                </footer>
            </div>
        </div> 

        <script>
            $(document).ready(function () {
                $("#responsive-panel").kendoResponsivePanel({
                    breakpoint: 768,
                    autoClose: false,
                    orientation: "top"
                });
            });
            function onclick(e) {
                $("#responsive-panel").getKendoResponsivePanel().toggle();
            }
        </script>

        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>